### ISSUE TITLE
[Feature]: Create community enrollment form

### ISSUE THREAD

**Issue by diegobugs** [ColoniasDev/landing#11]
### 📝 Feature description
> Describe in a detailed explanation what this features is intended for.
  
### ✓ TODO list    
- [ ] Create enrollment form page.
- [ ] Create form component.
- [ ] Connect form with supabase.
- [ ] Create a email service to automate form submitting.
  
### 🖥 Design
> Related designs for this feature.
    
- NA

### 🖇 Additional files or docs
> You can add link, files or anything that improves the feature request information.
