### ISSUE TITLE
[Feature]: Site header

### ISSUE THREAD

**Issue by diegobugs** [ColoniasDev/landing#5]
### 📝 Feature description
> Describe in a detailed explanation what this features is intended for.
Implement top header bar.
Header will include site logo (animated if possible), navigation links and enroll button.
  
### ✓ TODO list    
- [ ] Create navigation bar component.
- [ ] Add media resources.
- [ ] Add navigation configuration. (App routes)
  
### 🖥 Design
> Related designs for this feature.
    
- NA

### 🖇 Additional files or docs
> You can add link, files or anything that improves the feature request information.
Media resources at: https://drive.google.com/drive/folders/1BJkZ7X40ZlM8F-noVw0GG5I8L7XNOmuO?usp=sharing
